### ISSUE TITLE
Decrease left margin/indent

### ISSUE THREAD

**Issue by james-brown-ca** [SamRothCA/Today-Scripts#15]
Would it be possible to decrease the left margin/indent?  I have created a script that outputs a 2-month calendar (this and next) and highlights the current day and day of week, but it will not fit within the current constraints.

![todayscripts 2-month calendar](https://cloud.githubusercontent.com/assets/11192701/6370435/ea19e25a-bcc6-11e4-8a3a-f09fd0ef080e.png)

**Comment by SamRothCA** [comment]
Right now Today Scripts uses a fixed 40-character wide TTY. 40 fits nicely between the edit button and status indicator, but more space is always nicer, so I'll see if I can play with a design that ups this to 42.
