### ISSUE TITLE
Custom Labels

### ISSUE THREAD

**Issue by goose121** [SamRothCA/Today-Scripts#17]
Your README file says that there is a way to make those custom labels in the menu bar, but I can't find a tutorial anywhere. How do you make those?

**Comment by SamRothCA** [comment]
The "custom labels" are the names you create for each script. Today Scripts is a Notification Center widget. The items you see in my menu bar are those of [iStat Menus](http://bjango.com/mac/istatmenus/).

**Comment by goose121** [comment]
Sorry about that waste of time!
<facepalmToSelf />
