### ISSUE TITLE
How to use this for a long running process like a server

### ISSUE THREAD

**Issue by theinterned** [SamRothCA/Today-Scripts#18]
Hi, 

This is a great idea. I'd like to use this script to run things like elastic search, reds, rails etc.

I wonder if you could give me a hint / recipe for how that could be done?

Thanks

**Comment by SamRothCA** [comment]
I'm not personally familiar with any of those things... For "long running scripts" in general, one approach would be to direct the output of them to a pipe (or just a normal file), then have Today Scripts read from that.
