### ISSUE TITLE
How can I delete this Notification Center Widgate?

### ISSUE THREAD

**Issue by Lizy0123** [SamRothCA/Today-Scripts#36]

**Comment by rgkobashi** [comment]
You can delete as any other widget (click on the Edit button on the Today section and then on the minus symbol of the desired widget).
If you want to delete the app, go to Applications folder and then delete Today Scripts.app

**Comment by Lizy0123** [comment]
Yeah，but the trouble is that I didn't find Today Scripts.app，in the Applications folder

**Comment by Lizy0123** [comment]
Yeah，but the trouble is that I didn't find Today Scripts.app，in the Applications folder

**Comment by Lizy0123** [comment]
Yeah，but the trouble is that I didn't find Today Scripts.app，in the Applications folder

**Comment by rgkobashi** [comment]
Have you look on /Applications folder, instead of /Users/{your-user}/Applications?

**Comment by Lizy0123** [comment]
I think I know the reason. I install Today-Scripts through Xcode，so there  no Today Scripts.app。

 I solved this problem by download the Latest release，install it  and then delete it 。

 Thank you rgkobashi

**Comment by rgkobashi** [comment]
Oh that makes sense... however you can delete the Today Scripts.app generated by Xcode (locate the .app on Xcode project, right-click Show in Finder)

**Comment by Lizy0123** [comment]
Thank you. I didn't describe the problem clearly. I've got it. Thank you again.
