### ISSUE TITLE
Does anyone know how to configure iStats?

### ISSUE THREAD

**Issue by KyleKing** [SamRothCA/Today-Scripts#8]
I can run the command ```istats``` in term and terminal and I get the right result with:
```
--- CPU Stats ---
CPU temp: 53.0°C  ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system: 2
```
...etc

But when I put it in the Today Scripts editor it returns:
```command not found```

Checking the wiki, it says to use /bin/bash. I installed iStats with ```gem install iStats``` through RVM. 

I would appreciate any advice to help configure iStats!

**Comment by SamRothCA** [comment]
No problem, just run the following in Terminal:

    which istats

This will print out the full path to the program. Copy and paste that into Today Scripts, and you should be good.

**Comment by KyleKing** [comment]
Thanks Sam! I'm still having trouble though. The full path I got is: ```/Users/kyleking/.rvm/gems/ruby-2.1.1/bin/istats``` I pasted it directly into the editor, but it gave me an error: ```env: ruby_executable_hooks: No such file or directory```

This is what I have now:
! [image](http://snpy.link/dBPTtZ)

Do I need to set the $PATH AND 5ENV variables inside today scripts?

**Comment by amoeba** [comment]
Sam will probably pipe in for the reason why your rvm-installed iStats
isn't working but here's what I do. I use chruby instead of rvm, but I just
shim chruby into Today Scripts then run iStats. Here's my script:

    source /usr/local/share/chruby/chruby.sh
    chruby 2.1.5
    iStats

**Comment by KyleKing** [comment]
It turns out that its a problem with my $PATH variable. So I fixed it by uninstalling and re-installing RVM. Now everything works smoothly just with the command ```iStats```!

![Editor](http://snappyimages.nextwavesrl.netdna-cdn.com/img/34c39361f23e953b13629b4fd25d10bc.png)
![Output](http://snappyimages.nextwavesrl.netdna-cdn.com/img/37549d265f3b838259647b5cfd7d3697.png)

**Comment by SnShine** [comment]
I have faced the same problem. First find istats using `which stats`.
Then use the command `ruby <output of last command>` in Today-scripts to get the staus. Use `/bin/bash` in Today-scripts.
